version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "log-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  opensearch:
    image: opensearchproject/opensearch:latest
    #volumes:
      #- /var/www/html/log_analysis/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=CRCpFGDNe3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - elastic
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200", "http://opensearch:9200"]'  # Указывает на сервис opensearch в Docker Compose
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - opensearch

  logstash:
    image: logstash:7.13.4
    #command: tail -f /dev/null
    volumes:
    - /var/www/html/log_analysis/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - /var/www/html/log_analysis/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
    - "5000:5000"
    networks:
    - elastic
    depends_on:
    - opensearch

  filebeat:
    image: elastic/filebeat:7.8.0
    user: "0:0"
    volumes:
    - /var/www/html/log_analysis/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    - /var/log:/var/log
    networks:
    - elastic
    depends_on:
    - logstash

networks:
  elastic:
    driver: bridge